// <auto-generated />
using System;
using BookWorm.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookWorm.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookWorm.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1026),
                            DeletedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1028),
                            DisplayOrder = 1,
                            Name = "Fiction",
                            UpdatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1027)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1032),
                            DeletedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1033),
                            DisplayOrder = 2,
                            Name = "SciFic",
                            UpdatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1033)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1035),
                            DeletedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1036),
                            DisplayOrder = 3,
                            Name = "History",
                            UpdatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1036)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1121),
                            DeletedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1122),
                            DisplayOrder = 4,
                            Name = "Horror",
                            UpdatedAt = new DateTime(2023, 12, 10, 4, 27, 56, 500, DateTimeKind.Utc).AddTicks(1121)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
